### ISSUE TITLE
Why intervals changed?

### ISSUE THREAD

**Issue by HongyuanZhang** [appliedtopology/javaplex#21]
For metric.impl.ExplicitMetricSpace, do I need to call finalizeStream after I call api.Plex4.createVietorisRipsStream? My code is as follows:

M = csvread('150pcs1.csv'); // Distance Matrix 
m_space = metric.impl.ExplicitMetricSpace(M);
stream = api.Plex4.createVietorisRipsStream(m_space, 2, 7.5);
persistence = api.Plex4.getModularSimplicialAlgorithm(2, 2);
intervals = persistence.computeAnnotatedIntervals(stream);

Also, after I changed max_filtration, my bar codes graph and my intervals changed. Not only the end points of the intervals changed, but also the data points which form these intervals. For example, when I set max_filtration to 7.5, I got an interval 

[4.5, 5.625): [9,10] + [0,18] + [45,137] + [36,45] + [1,6] + [3,137] + [3,6] + [7,36] + [7,9] + [10,29] + [1,18] + [0,29], 

but after I changed max_filtration to 7, this interval changed to [4.55, 5.6): -[7,49] + [3,6] + [10,29] + [3,31] + [7,31] + [10,49] + [1,6] + [0,18] + [0,29] + [1,18]. I wonder why this happened. 

Hongyuan

**Comment by henryadams** [comment]
The reason why the inteval changed from [4,5, 5.625] to [4.55, 5.6) is explained in the second paragraph of Section 5 of the Javaplex tutorial:
http://www.math.colostate.edu/~adams/research/javaplex_tutorial.pdf
Indeed, Javaplex discretizes the scale parameters from 0 to max_filtration into some number of bins (which you can specify depending on the level of precision you want), and if you change max_filtration, then you change the width of each bin, and hence you change the discretized start and end time of each interval.

The representative cycle changing from [9,10] + [0,18] + [45,137] + [36,45] + [1,6] + [3,137] + [3,6] + [7,36] + [7,9] + [10,29] + [1,18] + [0,29] to -[7,49] + [3,6] + [10,29] + [3,31] + [7,31] + [10,49] + [1,6] + [0,18] + [0,29] + [1,18] is due to the fact that there are many different possible representative cycles for any single homology class! Javaplex always returns one such representative cycle --- there's no notion of a "canonical" representative cycle to return, and that's why Javaplex returns an essentially arbitrary one. I could point you to more references here if you like --- this is the representative cycle that is output by the standard persistence algorithm, and there are references I could point you to here.
